export { default as SmartPhone } from './SmartPhone'
export { default as Laptop } from './Laptop'
export { default as Tablet } from './Tablet'
export { default as Accessories } from './Accessories'
export { default as InfoProductClient } from './InfoProductClient'